### ISSUE TITLE
README.md里面的server例子不能用

### ISSUE THREAD

**Issue by lsm** [node-modules/weibo#1]
是不是doc老了？

```
var tapi = require('weibo').tapi;
tapi.init('tsina', appkey, secret);
tapi.public_timeline(function(error, data, response) {
    if(error) {
        console.error(error);
    } else {
        console.log(data);
    }
});
```

错误信息：

```
/path/to/node_modules/weibo/lib/tsina.js:191
        callback.call(context, error, data, res);
           ^
TypeError: Cannot call method 'call' of undefined
at Object.<anonymous> (/path/to/node_modules/weibo/lib/tsina.js:191:16)
at IncomingMessage.<anonymous> (/path/to/node_modules/weibo/lib/urllib.js:101:14)
at IncomingMessage.emit (events.js:81:20)
at HTTPParser.onMessageComplete (http.js:133:23)
at Socket.ondata (http.js:1213:22)
at Socket._onReadable (net.js:681:27)
at IOWatcher.onReadable [as callback] (net.js:177:10)
```

**Comment by fengmk2** [comment]
呃，我疏忽了，没加请求参数，你改成这样吧。非常感谢你的提醒！[?][?]

tapi.public_timeline({}, function(error, data, response) {
       if(error) {
           console.error(error);
       } else {
           console.log(data);
       }
   });

On Fri, May 6, 2011 at 10:52 AM, zir <
reply@reply.github.com>wrote:

> tapi.public_timeline(function(error, data, response) {
>        if(error) {
>            console.error(error);
>        } else {
>            console.log(data);
>        }
>    });

## 

MK2

---

_记得当时年纪小/
你爱谈天，我爱笑/
有一回并肩坐在桃树下/
风在林梢鸟儿在叫/
我们不知怎样睡着了/
梦里花落知多少_

**Comment by lsm** [comment]
好吧，有个api文档就好了
