### ISSUE TITLE
TypeError: Object #<Object> has no method 'oauth'

### ISSUE THREAD

**Issue by kinhunt** [node-modules/weibo#15]
谢谢你的贡献，这是一个非常有用的项目。

我在运行演示的时候

node connect_with_oauth_middleware

出现以下错误，请问是什么原因？

TypeError: Object #<Object> has no method 'oauth'
    at Object.<anonymous> (/data/www/node/node_modules/weibo/examples/connect_with_oauth_middleware.js:30:9)

谢谢

**Comment by fengmk2** [comment]
请先使用0.3.2版本，0.4+版本还没稳定。

npm install weibo@0.3.2

---

MK2, FaWave, Net4Team ☺
TEL: 18668079069
微博: @Python发烧友
Twitter: @fengmk2
Blog: http://fengmk2.cnblogs.com/

**Comment by kinhunt** [comment]
谢谢
