### ISSUE TITLE
通过这些修改,才能运行起来[新浪微薄]

### ISSUE THREAD

**Issue by dreampuf** [node-modules/weibo#2]
lib/oauth_middleware.js

r173:
    //options.home_url = home_url.replace(/\/+$/, '');
    options.home_url = options.home_url.replace(/\/+$/, '');

r179:

```
if(!options.callback_path) {
    options.callback_path = options.login_path + '_callback';
}
```

lib/tapi.js

r51 下插入

```
user.blogType = user.blogType == 'undefined' ? undefined : user.blogType;
```

**Comment by fengmk2** [comment]
已经修复这些问题，并且oauth_middleware模块也重构了，请查看examples里面的使用例子。
