### ISSUE TITLE
运行connect_with_oauth_middleware.js例子问题

### ISSUE THREAD

**Issue by scottkiss** [node-modules/weibo#20]
node新手，求问connect_with_oauth_middleware.js例子执行到用户授权页面后，用户登录并授权后，报500错误，控制台显示undefined，本地测试的。求解惑T_T

**Comment by tans** [comment]
是回调执行报错吗?

**Comment by scottkiss** [comment]
是的~

**Comment by fengmk2** [comment]
@scottkiss 你是直接使用`$ node examples/connect_with_oauth_middleware.js` 来运行的吗？

**Comment by scottkiss** [comment]
@fengmk2 是的，运行环境是在windows下，回调后就undefined，看了下，好像错误是在oauth_middleware.js文件的r78行tapi.verify_credentials(accessToken, function (err, user) {
      if (err) {}这个地方捕捉到的，我主要是针对sina微博的测试，我是在本地测试的，没有使用域名，不知道是不是这个原因，还是callback地址需要什么特别的吗？

**Comment by fengmk2** [comment]
你没有修改appkey吧？我本地测试是可以授权的。

**Comment by scottkiss** [comment]
@fengmk2  我擦类，找到原因了，原来是我的新浪应用还没审核。。。用的AppKey无效导致的。。。。。嘿嘿。。感谢T_T @fengmk2
