### ISSUE TITLE
Sina Weibo V2 支持

### ISSUE THREAD

**Issue by kinhunt** [node-modules/weibo#22]
hi，请问当前版本是否支持 V2 API？

**Comment by vingel** [comment]
我看代码貌似不支持，请问作者有支持的计划么？

没有我就要自己写一个啦。

**Comment by fengmk2** [comment]
## 我计划在国庆期间才有时间做。

MK2, FaWave, Net4Team ☺nodejs
TEL: 18668079069
Github: https://github.com/fengmk2
微博: @Python发烧友
Twitter: @fengmk2
CNode: http://cnodejs.org/user/suqian
Blog: http://fengmk2.github.com/

**Comment by guo-yu** [comment]
跪求。。。

**Comment by fengmk2** [comment]
Hi all, weibo@0.6.1 now support weibo api v2.

**Comment by fengmk2** [comment]
@kinhunt @vingel @turingou 各位，已经支持了，请试试。

**Comment by fengmk2** [comment]
大家先看看统一后的api文档，会很清晰的 https://github.com/fengmk2/node-weibo/blob/master/api.md

**Comment by kinhunt** [comment]
excellent job!!! thank you.

中秋快乐

**Comment by guo-yu** [comment]
thx
中秋快乐~
