### ISSUE TITLE
Use Everyauth as a middleware

### ISSUE THREAD

**Issue by clemsos** [node-modules/weibo#24]
I am writing an app and I use everyauth to manage all oauth process. I can do oauth login with weibo using everyauth then get accessToken. How could I use it directly with node-weibo to make api requests ? Any idea or advices? 

Thanks for the good job anyway ! Very useful :)

**Comment by fengmk2** [comment]
You can see the [test/config.js](https://github.com/fengmk2/node-weibo/blob/master/test/config.js), set blogtype to `'weibo'` and set the access_token you got from everyauth.

``` js
var user = {
  blogtype: 'weibo',
  access_token: 'your got from everyauth',
};
```

Then use the custom user to call like this:

``` js
var weibo = require('weibo');
weibo.init('weibo', 'your appkey', 'your sercect', 'oob');
weibo.user_timeline(user, function (err, data) {
   console.log(data);
});
```

**Comment by clemsos** [comment]
It works :+1: 
Thanks a lot ! 
and thanks for this node-weibo SDK !
