### ISSUE TITLE
自带示例本地测试sina, error:redirect_uri_mismatch

### ISSUE THREAD

**Issue by atian25** [node-modules/weibo#25]
搜索了下, 好像说不支持localhost?

引导界面是:  https://api.weibo.com/oauth2/authorize?redirect_uri=http%3A%2F%2Flocalhost%3A8088%2Fauth%2Fcallback&client_id=2450506061&response_type=code

配置了host好像也不行
配置homeurl会报错

**Comment by atian25** [comment]
放到NAE后, 运行.
授权后跳转到
http://weibotest.dev.cnodejs.net/auth/callback?type=weibo&oauth_token=f81fcb8d1cbd907dfc924d03d46e3796&oauth_verifier=686228

界面就输出[object Object]

后台提示:
TypeError: Cannot call method 'get_access_token' of undefined
[object Object]

**Comment by atian25** [comment]
@fengmk2  请问是我漏了哪步吗?

**Comment by fengmk2** [comment]
是参考这个的？ https://github.com/fengmk2/node-weibo/blob/master/examples/connect_with_oauth_middleware.js

**Comment by fengmk2** [comment]
新浪需要跟你后台设置的domain一致才会正确跳转的。

**Comment by atian25** [comment]
@fengmk2 嗯,配过了.

https://gist.github.com/605814d36b374b09f705
- sina配置界面已经配置应用地址/授权回调页为: http://weibotest.dev.cnodejs.net/auth/callback
- sina登录后返回的url是: http://weibotest.dev.cnodejs.net/auth/callback?type=weibo&oauth_token=b293522346091388fb1ea60f6958b0eb&oauth_verifier=829586
- 界面呈现[object Object],后台输出console.log('xx3',user)是undefined
