### ISSUE TITLE
是否支持腾讯微博的私信?

### ISSUE THREAD

**Issue by atian25** [node-modules/weibo#26]
快速了翻了下源码, 好像是有direct_message_create的,而且tqq也有.
但是写了个测试,

<pre><code>
  weibo.direct_message_create({
    "oauth_token": "some token",
    "oauth_token_secret": "some secret",
    "blogtype": "tqq",
    "authtype": "oauth"
  },'some id','some content',function(err,result){
    console.log(err,result)
  })
</code></pre>

报错是: `TypeError: Object #<TQQAPI> has no method 'direct_message_create'`

**Comment by fengmk2** [comment]
[message_create](https://github.com/fengmk2/node-weibo/blob/master/api.md#message_create) 私信我还没实现，我现在看看是否能实现一下。

**Comment by fengmk2** [comment]
```
DirectMessageCreateError: have no right, please connect our DB to add your app to white list
```

现在腾讯微博私信也要商务授权了吧。

**Comment by atian25** [comment]
刚看到：·公告：由于本API最近发现有些开发者不遵循开发规范，有严重的恶意发送私信操作，被大量用户举报，现临时决定关闭此API的调用权限，需要使用私信的应用，可以联系商务联系人发送邮件，申请私信接口权限!·

**Comment by fengmk2** [comment]
@atian25 已经支持 `direct_message_create()` 了。

**Comment by fengmk2** [comment]
文档可以查看: https://github.com/fengmk2/node-weibo/blob/master/api.md#direct_message_create

**Comment by atian25** [comment]
@fengmk2  thanks。

PS： 新浪微博的那个新手issue有什么建议不？
