### ISSUE TITLE
README.md 中的 entry.js 无法正常运行

### ISSUE THREAD

**Issue by KJlmfe** [node-modules/weibo#31]
你好，我的nodejs版本是v0.10.4 按照你README中说的方法，在执行 node entry.js 后:

{ [PublicTimelineError: source paramter(appkey) is missing]
  data:
   { error: 'source paramter(appkey) is missing',
     error_code: 10006,
     request: '/2/statuses/public_timeline.json' },
  name: 'PublicTimelineError' }

但是，我在weibo.init()中明明有填入appkey。

**Comment by NStal** [comment]
我遇到了同样的问题.

**Comment by zliu9** [comment]
同样的问题，作者能否看看这个bug

**Comment by fengmk2** [comment]
因为使用了oauth2，又由于没有登录授权，所以需要手动增加一个source参数: `var cursor = {count: 20, source: appkey};`

``` js
var weibo = require('../../');

// change appkey to yours
var appkey = 'your appkey';
var secret = 'your app secret';
var oauth_callback_url = 'your callback url';
weibo.init('weibo', appkey, secret, oauth_callback_url);

var user = { blogtype: 'weibo' };
var cursor = {count: 20, source: appkey};
weibo.public_timeline(user, cursor, function (err, statuses) {
  if (err) {
    console.error(err);
  } else {
    console.log(statuses);
  }
});
```
