### ISSUE TITLE
授权redirect_url不匹配

### ISSUE THREAD

**Issue by hbbalfred** [node-modules/weibo#32]
先提一个小错误，oauth_middleware.js里

``` js
options.logoutPath = options.logoutPath || '/ouath/logout';
```

缺省参数拼错了 **oauth**

我主要想说的是，一开始我是在localhost:3000下测试的，因为要绑定域名，再没有重启服务器的时候，直接改了host然后从test.com进入程序，但此时options.homeUrl依旧是之前的localhost:3000（设置路由的时候没有指定homeUrl）导致`var authCallback = getAuthCallback(options);` 的host部分不是test.com从而出现问题。

情况比较奇葩...不过似乎把login里对homeUrl的判断去掉，每次从header里更新，也没什么问题？

**Comment by fengmk2** [comment]
是存在问题，你能否帮忙修复一下呢？
在 2013-5-16 PM6:15，"hbb" notifications@github.com写道：

**Comment by fengmk2** [comment]
@hbbalfred Thanks, I had been publish weibo@0.6.9
