### ISSUE TITLE
weibo api 2.0的access token过期问题有啥好方案么？

### ISSUE THREAD

**Issue by RobinQu** [node-modules/weibo#34]
RT～
sina没有给refresh token；难道没24个小时重新auth？

自己的使用场景很简单，网站专用一个weibo帐号，网站发布的新内容想同步一份到weibo上。

**Comment by fengmk2** [comment]
如果你是做爬虫的话，可以维护一个accesstoken列表。
如果是网站的话，你做一个定时检测，过期了发邮件告诉你，然后你重新授权。
在 2013-6-16 PM1:10，"RobinQu" notifications@github.com写道：

**Comment by RobinQu** [comment]
多谢解答。。。。。

干脆网站后台登陆就用weibo来认证吧，这样每次上去accessToken都是新的。。。泪。。。

**Comment by RobinQu** [comment]
最后使用passport、passport-weibo直接做了站点的后台认证模块，就为了拿新鲜的access_token。汗......
为了后台安全，最后又加了个基于totp的two-factored认证
