### ISSUE TITLE
git summary

### ISSUE THREAD

**Issue by wxianfeng** [node-modules/weibo#35]
看到 Readme 中 每个  author 代码量的统计, 很直观, 请问是什么tool 统计出来的, 能给个链接不?

@fengmk2

**Comment by fengmk2** [comment]
tj的 https://github.com/visionmedia/git-extras
在 2013-10-19 PM10:02，"xianfeng wang" notifications@github.com写道：

**Comment by wxianfeng** [comment]
awesome!!!
