### ISSUE TITLE
oauth_middleware

### ISSUE THREAD

**Issue by rench** [node-modules/weibo#4]
oauth_middleware里面的options里面的参数callback_path 你写死了,不能传参数

options.callback_path = options.login_path + '_callback';

modify:

options.callback_path = options.callback_path || options.login_path + '_callback';

**Comment by fengmk2** [comment]
这个callback处理应该是自动化的，有模块自己来处理就好了。有什么场景下要自己处理呢？

**Comment by fengmk2** [comment]
请使用最新版本。
