### ISSUE TITLE
Missing parts

### ISSUE THREAD

**Issue by snowman-repos** [node-modules/weibo#48]
e.g. http://open.weibo.com/wiki/2/statuses/queryid

There is no weibo.queryid for converting mid to id...

**Comment by fengmk2** [comment]
@darryl-snow there is no need to call queryid api to convert mid to id, just use [weibo-mid](https://github.com/node-modules/weibo-mid) to do that:

``` js
var mid = require('weibo-mid');

mid.encode('3600375418559878').should.equal('A09LvzUOy');
mid.decode('A09LvzUOy').should.equal('3600375418559878');
```

**Comment by fengmk2** [comment]
@darryl-snow I think I misunderstand your request...

**Comment by snowman-repos** [comment]
Just been playing with the SDK today, having a hard time matching up https://github.com/node-modules/weibo/blob/master/api.md with http://open.weibo.com/wiki/%E5%BE%AE%E5%8D%9AAPI. E.g. trying to do this: http://open.weibo.com/wiki/2/attitudes/create/en.
